version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PRIVATE_KEY=22c8052a1a03a9c674b9b5012161b57f5101b621f70105573b1dfde7a723a712
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
    #Hardcoded values for development and testing purposes
      - MONGO_URL=mongodb://mongodb:27017/coupon_system
      - PRIVATE_KEY=22c8052a1a03a9c674b9b5012161b57f5101b621f70105573b1dfde7a723a712
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
