version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - '5001:5001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongodb:27017/coupon_system
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
