version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      #Hardcoded values for development and testing purposes
      - REACT_APP_PRIVATE_KEY=22c8052a1a03a9c674b9b5012161b57f5101b621f70105573b1dfde7a723a712
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5001/
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      #Hardcoded values for development and testing purposes
      - MONGO_URL=mongodb://mongodb:27030/coupon_system
      - PRIVATE_KEY=22c8052a1a03a9c674b9b5012161b57f5101b621f70105573b1dfde7a723a712
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    command:
      [
        "mongod",
        "--dbpath",
        "/data/db",
        "--port",
        "27030",
        "--profile",
        "1",
        "--slowms",
        "1",
      ]
    volumes:
      - ./mongo_data:/data/db
    container_name: mongodb
    ports:
      - "27030:27030"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
